# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170708_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
