# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170707_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
