# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170708_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrips',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='usertrips',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='usertrips',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='usertrips',
            name='starttime',
        ),
        migrations.AddField(
            model_name='usertrips',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 12, 26, 42, 648454, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertrips',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 12, 26, 55, 5075, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
