# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170709_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('acttype', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=300)),
                ('time', models.IntegerField()),
                ('book', models.CharField(max_length=50)),
            ],
        ),
    ]
