# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_locations_locid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='actuals',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trips',
            name='possibles',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trips',
            name='tripid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
