# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_locations_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=100)),
                ('tripid', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('locid', models.IntegerField()),
                ('booked', models.IntegerField()),
                ('booktime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='trips',
            name='actualstime',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
