# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-20 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20170720_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booktime',
        ),
    ]
