# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_remove_bookings_booktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='homecoordinates',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trips',
            name='homedistances',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trips',
            name='homename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
