# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20170725_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booked',
        ),
    ]
