# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_remove_bookings_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
