# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_trips_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('locid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('hashtag', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('imagelink', models.CharField(max_length=500)),
                ('time', models.IntegerField()),
                ('rating', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('book', models.CharField(max_length=50)),
                ('deposit', models.IntegerField()),
                ('acttype', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=300)),
                ('provider', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
            ],
        ),
    ]
