# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_locstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='price',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
