# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20170805_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='hashtag',
            field=models.CharField(default='#Popular', max_length=200),
            preserve_default=False,
        ),
    ]
