# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20170807_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('originid', models.IntegerField()),
                ('destid', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
