# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_distances'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='email',
            field=models.CharField(default='axgoel8@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
