# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-15 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_trips_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='paysum',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
