# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='phone',
            field=models.CharField(default='9', max_length=200),
            preserve_default=False,
        ),
    ]
